### PR TITLE
Pr2 finished already

### PR DESCRIPTION
**Pull request by alemdar1**
added all codes here

### CODE REVIEW

**Comment by alemdar1** [comment]
jkj

**Comment by MiroPetkov2000** [comment]
Hi Alemdar. Let's try to merge this branch 👍

**Review by MiroPetkov2000 — APPROVED** [review]
All looks great

**Comment by MiroPetkov2000** [comment]
Ok, I approved it. You can merge now :)

**Review by shvedusa — COMMENTED** [review]
The code looks very powerful to me )) @alemdar1

**Review by shvedusa — APPROVED** [review]

**Pull request merged**
