### PR TITLE
Let's start working together

### PR DESCRIPTION
**Pull request by MiroPetkov2000**
Hi Guys. Let's start working together!

### CODE REVIEW

**Comment by yourMD12** [comment]
lets do that

**Comment by MiroPetkov2000** [comment]
Hi Guys, can yo u please review so we can merge the branch to master :) Thanks

**Review by yourMD12 — APPROVED** [review]

**Comment by shvedusa** [comment]
Looks like @burcuozr  deleted the branch ))))) lol

**Comment by shvedusa** [comment]
Did you delete miro_git_class again? Miro

**Pull request merged**
